codecov:
  notify:
    wait_for_ci: true

ignore:
  - 'packages/eslint-config'
  - 'packages/rsbuild-config'
  - 'packages/storybook-config'

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        range: 10%
      stl:
        target: 80%
        flags:
          - stl
      ui:
        target: 80%
        flags:
          - ui
      ui-storybook:
        target: 80%
        flags:
          - ui-storybook
      www:
        target: 80%
        flags:
          - www
      www-storybook:
        target: 80%
        flags:
          - www-storybook

flags:
  stl:
    paths:
      - packages/stl
  ui:
    paths:
      - packages/ui
  ui-storybook:
    paths:
      - packages/ui
  www:
    paths:
      - services/www
  www-storybook:
    paths:
      - services/www
