apiVersion: v1
kind: Secret
metadata:
  name: umami-secrets
  namespace: com-ermnvldmr
type: Opaque
stringData:
  APP_SECRET: "CHANGE_ME_IN_ENCRYPTED_SOPS_SECRET"
  DATABASE_URL: "postgresql://umami:CHANGE_ME@postgres-service.com-ermnvldmr.svc.cluster.local:5432/umami"
