apiVersion: v1
kind: Service
metadata:
  name: umami-service
  namespace: com-ermnvldmr
spec:
  type: ClusterIP
  selector:
    app: umami
  ports:
    - name: http
      port: 3000
      targetPort: 3000
