apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: com-ermnvldmr
data:
  postgresql.conf: |
    # Low-memory tuned configuration for single-node K3s VM
    listen_addresses = '*'
    max_connections = 50
    shared_buffers = 64MB
    effective_cache_size = 128MB
    maintenance_work_mem = 16MB
    checkpoint_completion_target = 0.9
    wal_buffers = 2MB
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    work_mem = 4MB
    min_wal_size = 80MB
    max_wal_size = 512MB
